baseurl: "/"
languageCode: "en-us"
title: "Germano Barcelos"
theme: "xmin"
googleAnalytics: "G-4ZJW0EGHSC"
disqusShortname: "gegen07"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
publishdir: public

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Publications
      url: "publications/"
      weight: 2
    - name: Blog
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "[Github](https://github.com/gegen07) | [Twitter](https://twitter.com/gegen_07)"
  custom_css: ["css/style.css"]
  custom_fonts: ["css/fonts.css"]

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
